package models.entities.references.specialites;

public enum SpecialiteAAE {
    ANALYSTE_INVESTIGATION_NUMERIQUE,
    AUDITEUR_CYBECURITE,
    CHARGEE_DE_PROJETS_SSI,
    INGENIEUR_CYBERPROTECTION,
    TECHNICIEN_SIC_AERONAUTIQUE,
    RESPONSABLE_SYSTEMES_NUMERIQUE
}
