package model.entities.references;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum SpecialiteMN {
    MATELOT_DE_LA_FLOTE,
    CARISTE_MAGASINIER,
    CHAUFFEUR_POIDS_LOURDS,
    MECANICIEN_NAVAL,
    OPERATEUR_SYSTEMES_INFORMATION_COMMUNICATION,
    HYDROGRAPHE,
    ELECTROTECHNICIEN,
    CUISINIER,
    POMPIER_DE_LA_MARINE,
    CANONNIER,
    MARIN_PECHEUR,
    PLONGEUR_DEMINEUR,
    SPECIALISTE_EN_TELECOMMUNICATIONS,
    METEOROLOGISTE,
    NAVIGATEUR,
    CHEF_DE_QUART,
    OFFICIER_MARINIER,
    TECHNICIEN_LOGISTIQUE,
    TECHNICIEN_DE_MAINTENANCE_AERONAUTIQUE,
    TECHNICIEN_SYSTEMES_ARMEMENT,
    TECHNICIEN_COMMUNICATION,
    TECHNICIEN_ELECTRONIQUE,
    TECHNICIEN_SECURITE_PROTECTION_ENVIRONNEMENT,
    TECHNICIEN_MECANIQUE_NAVALE,
    MECANICIEN_MOTORISTE,
    SPECIALISTE_RENSEIGNEMENT,
    PILOTE_DE_CHASSE,
    PILOTE_D_HELICOPTERE,
    PILOTE_DE_DRONE,
    OFFICIER_DE_LA_MARINE_MARCHANDE,
    OFFICIER_DE_GUERRE,
    OFFICIER_DE_RENSEIGNEMENT,
    OFFICIER_DE_DEFENSE_SOL_AIR,
    OFFICIER_DE_LA_NAVIGATION,
    OFFICIER_MECANICIEN,
    OFFICIER_SYSTEME_INFORMATION_COMMUNICATION,
    INGENIEUR_AEROSPATIAL,
    COMMANDANT_DE_BORD_AERONAVALE,
    MEDECIN_DE_LA_MARINE,
    PSYCHOLOGUE_DE_LA_MARINE,
    INGENIEUR_LOGISTIQUE,
    RESPONSABLE_EN_COMMUNICATION_RELATIONS_PUBLIQUES,
    AMIRAL,
    VICE_AMIRAL,
    CONTRE_AMIRAL,
    AMIRAL_DE_LA_FLOTE;

    public static List<String> getListSpecialiteMNToString() {
        return Arrays.stream(values())
                .map(Enum::name)
                .collect(Collectors.toList());
    }
}
